/* Generated by Pyrex 0.9.3.1 on Fri Aug 11 09:57:26 2006 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "string.h"
#include "ctype.h"
#include "stdlib.h"
#include "double_metaphone.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from fuzzy */

staticforward PyTypeObject __pyx_type_5fuzzy_Soundex;

struct __pyx_obj_5fuzzy_Soundex {
  PyObject_HEAD
  int size;
  char (*map);
};

staticforward PyTypeObject __pyx_type_5fuzzy_DMetaphone;

struct __pyx_obj_5fuzzy_DMetaphone {
  PyObject_HEAD
  int size;
};

static PyTypeObject *__pyx_ptype_5fuzzy_Soundex = 0;
static PyTypeObject *__pyx_ptype_5fuzzy_DMetaphone = 0;
static PyObject *__pyx_k1;

/* Implementation of fuzzy */

static char (__pyx_k2[]) = "01230120022455012623010202";

static int __pyx_f_5fuzzy_7Soundex___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5fuzzy_7Soundex___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_size = 0;
  int __pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"size",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_size)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_size);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":16 */
  __pyx_1 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  ((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->size = __pyx_1;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":17 */
  ((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->map = __pyx_k2;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("fuzzy.Soundex.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_size);
  return __pyx_r;
}

static PyObject *__pyx_f_5fuzzy_7Soundex___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5fuzzy_7Soundex___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_s = 0;
  char (*__pyx_v_cs);
  int __pyx_v_ls;
  int __pyx_v_i;
  int __pyx_v_written;
  char (*__pyx_v_out);
  PyObject *__pyx_v_pout;
  PyObject *__pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"s",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_s)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_s);
  __pyx_v_pout = Py_None; Py_INCREF(__pyx_v_pout);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":26 */
  __pyx_v_written = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":28 */
  __pyx_v_out = ((char (*))malloc((((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->size + 1)));

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":29 */
  __pyx_1 = PyString_AsString(__pyx_v_s); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_v_cs = __pyx_1;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":30 */
  __pyx_v_ls = strlen(__pyx_v_cs);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":31 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_ls; ++__pyx_v_i) {

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":32 */
    __pyx_2 = ((__pyx_v_cs[__pyx_v_i]) >= 97);
    if (__pyx_2) {
      __pyx_2 = ((__pyx_v_cs[__pyx_v_i]) <= 122);
    }
    if (__pyx_2) {

      /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":33 */
      (__pyx_v_cs[__pyx_v_i]) = ((__pyx_v_cs[__pyx_v_i]) - 32);
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":34 */
    __pyx_2 = ((__pyx_v_cs[__pyx_v_i]) >= 65);
    if (__pyx_2) {
      __pyx_2 = ((__pyx_v_cs[__pyx_v_i]) <= 90);
    }
    if (__pyx_2) {

      /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":35 */
      __pyx_2 = (__pyx_v_written == 0);
      if (__pyx_2) {

        /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":36 */
        (__pyx_v_out[__pyx_v_written]) = (__pyx_v_cs[__pyx_v_i]);

        /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":37 */
        __pyx_v_written = (__pyx_v_written + 1);
        goto __pyx_L6;
      }
      __pyx_2 = ((((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->map[((__pyx_v_cs[__pyx_v_i]) - 65)]) != 48);
      if (__pyx_2) {
        __pyx_2 = (__pyx_v_written == 1);
        if (!__pyx_2) {
          __pyx_2 = ((__pyx_v_out[(__pyx_v_written - 1)]) != (((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->map[((__pyx_v_cs[__pyx_v_i]) - 65)]));
        }
      }
      if (__pyx_2) {

        /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":40 */
        (__pyx_v_out[__pyx_v_written]) = (((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->map[((__pyx_v_cs[__pyx_v_i]) - 65)]);

        /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":41 */
        __pyx_v_written = (__pyx_v_written + 1);
        goto __pyx_L6;
      }
      __pyx_L6:;
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":42 */
    __pyx_2 = (__pyx_v_written == ((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->size);
    if (__pyx_2) {

      /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":43 */
      goto __pyx_L3;
      goto __pyx_L7;
    }
    __pyx_L7:;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":44 */
  __pyx_2 = ((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->size;
  for (__pyx_v_i = __pyx_v_written; __pyx_v_i < __pyx_2; ++__pyx_v_i) {

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":45 */
    (__pyx_v_out[__pyx_v_i]) = 48;
    __pyx_L8:;
  }
  __pyx_L9:;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":46 */
  (__pyx_v_out[((struct __pyx_obj_5fuzzy_Soundex *)__pyx_v_self)->size]) = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":48 */
  __pyx_3 = PyString_FromString(__pyx_v_out); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_v_pout);
  __pyx_v_pout = __pyx_3;
  __pyx_3 = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":49 */
  free(__pyx_v_out);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":51 */
  Py_INCREF(__pyx_v_pout);
  __pyx_r = __pyx_v_pout;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("fuzzy.Soundex.__call__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_pout);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_s);
  return __pyx_r;
}

static int __pyx_f_5fuzzy_10DMetaphone___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5fuzzy_10DMetaphone___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_size = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"size",0};
  __pyx_v_size = __pyx_k1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_size)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_size);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":60 */
  __pyx_1 = __pyx_v_size;
  Py_INCREF(__pyx_1);
  __pyx_2 = PyObject_IsTrue(__pyx_1); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  if (!__pyx_2) {
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyInt_FromLong(99999); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  }
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_5fuzzy_DMetaphone *)__pyx_v_self)->size = __pyx_2;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fuzzy.DMetaphone.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_size);
  return __pyx_r;
}

static PyObject *__pyx_f_5fuzzy_10DMetaphone___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5fuzzy_10DMetaphone___call__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_s = 0;
  char (*__pyx_v_cs);
  char (*(*__pyx_v_out));
  PyObject *__pyx_v_o1;
  PyObject *__pyx_v_o2;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"s",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_s)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_s);
  __pyx_v_o1 = Py_None; Py_INCREF(__pyx_v_o1);
  __pyx_v_o2 = Py_None; Py_INCREF(__pyx_v_o2);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":65 */
  __pyx_v_out = ((char (*(*)))malloc(((sizeof(char (*))) * 2)));

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":66 */
  __pyx_1 = PyString_AsString(__pyx_v_s); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_v_cs = __pyx_1;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":67 */
  DoubleMetaphone(__pyx_v_cs,__pyx_v_out);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":68 */
  __pyx_2 = PyString_FromString((__pyx_v_out[0])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_v_o1);
  __pyx_v_o1 = __pyx_2;
  __pyx_2 = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":69 */
  __pyx_2 = PyString_FromString((__pyx_v_out[1])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_v_o2);
  __pyx_v_o2 = __pyx_2;
  __pyx_2 = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":70 */
  __pyx_3 = ((__pyx_v_out[0]) != 0);
  if (__pyx_3) {

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":71 */
    free((__pyx_v_out[0]));
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":72 */
  __pyx_3 = ((__pyx_v_out[1]) != 0);
  if (__pyx_3) {

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":73 */
    free((__pyx_v_out[1]));
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":75 */
  free(__pyx_v_out);

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":77 */
  if (PyObject_Cmp(__pyx_v_o1, __pyx_v_o2, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_3 = __pyx_3 == 0;
  if (__pyx_3) {

    /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":78 */
    Py_INCREF(Py_None);
    Py_DECREF(__pyx_v_o2);
    __pyx_v_o2 = Py_None;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":80 */
  __pyx_2 = __pyx_v_o1;
  Py_INCREF(__pyx_2);
  __pyx_3 = PyObject_IsTrue(__pyx_2); if (__pyx_3 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (__pyx_3) {
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PySequence_GetSlice(__pyx_v_o1, 0, ((struct __pyx_obj_5fuzzy_DMetaphone *)__pyx_v_self)->size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  }
  __pyx_3 = PyObject_IsTrue(__pyx_2); if (__pyx_3 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (!__pyx_3) {
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = Py_None;
    Py_INCREF(__pyx_2);
  }
  __pyx_4 = __pyx_v_o2;
  Py_INCREF(__pyx_4);
  __pyx_3 = PyObject_IsTrue(__pyx_4); if (__pyx_3 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (__pyx_3) {
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_4 = PySequence_GetSlice(__pyx_v_o2, 0, ((struct __pyx_obj_5fuzzy_DMetaphone *)__pyx_v_self)->size); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  }
  __pyx_3 = PyObject_IsTrue(__pyx_4); if (__pyx_3 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (!__pyx_3) {
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_4 = Py_None;
    Py_INCREF(__pyx_4);
  }
  __pyx_5 = PyList_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_5, 0, __pyx_2);
  PyList_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_2 = 0;
  __pyx_4 = 0;
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("fuzzy.DMetaphone.__call__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_o1);
  Py_DECREF(__pyx_v_o2);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_s);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_5fuzzy_Soundex(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5fuzzy_Soundex *p = (struct __pyx_obj_5fuzzy_Soundex *)o;
  return o;
}

static void __pyx_tp_dealloc_5fuzzy_Soundex(PyObject *o) {
  struct __pyx_obj_5fuzzy_Soundex *p = (struct __pyx_obj_5fuzzy_Soundex *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5fuzzy_Soundex(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5fuzzy_Soundex *p = (struct __pyx_obj_5fuzzy_Soundex *)o;
  return 0;
}

static int __pyx_tp_clear_5fuzzy_Soundex(PyObject *o) {
  struct __pyx_obj_5fuzzy_Soundex *p = (struct __pyx_obj_5fuzzy_Soundex *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_5fuzzy_Soundex[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Soundex = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Soundex = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Soundex = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Soundex = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_5fuzzy_Soundex = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "fuzzy.Soundex", /*tp_name*/
  sizeof(struct __pyx_obj_5fuzzy_Soundex), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5fuzzy_Soundex, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Soundex, /*tp_as_number*/
  &__pyx_tp_as_sequence_Soundex, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Soundex, /*tp_as_mapping*/
  0, /*tp_hash*/
  __pyx_f_5fuzzy_7Soundex___call__, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Soundex, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5fuzzy_Soundex, /*tp_traverse*/
  __pyx_tp_clear_5fuzzy_Soundex, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5fuzzy_Soundex, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5fuzzy_7Soundex___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5fuzzy_Soundex, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_5fuzzy_DMetaphone(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5fuzzy_DMetaphone *p = (struct __pyx_obj_5fuzzy_DMetaphone *)o;
  return o;
}

static void __pyx_tp_dealloc_5fuzzy_DMetaphone(PyObject *o) {
  struct __pyx_obj_5fuzzy_DMetaphone *p = (struct __pyx_obj_5fuzzy_DMetaphone *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5fuzzy_DMetaphone(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5fuzzy_DMetaphone *p = (struct __pyx_obj_5fuzzy_DMetaphone *)o;
  return 0;
}

static int __pyx_tp_clear_5fuzzy_DMetaphone(PyObject *o) {
  struct __pyx_obj_5fuzzy_DMetaphone *p = (struct __pyx_obj_5fuzzy_DMetaphone *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_5fuzzy_DMetaphone[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_DMetaphone = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_DMetaphone = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_DMetaphone = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_DMetaphone = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_5fuzzy_DMetaphone = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "fuzzy.DMetaphone", /*tp_name*/
  sizeof(struct __pyx_obj_5fuzzy_DMetaphone), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5fuzzy_DMetaphone, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_DMetaphone, /*tp_as_number*/
  &__pyx_tp_as_sequence_DMetaphone, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_DMetaphone, /*tp_as_mapping*/
  0, /*tp_hash*/
  __pyx_f_5fuzzy_10DMetaphone___call__, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_DMetaphone, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5fuzzy_DMetaphone, /*tp_traverse*/
  __pyx_tp_clear_5fuzzy_DMetaphone, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5fuzzy_DMetaphone, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5fuzzy_10DMetaphone___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5fuzzy_DMetaphone, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initfuzzy(void); /*proto*/
DL_EXPORT(void) initfuzzy(void) {
  PyObject *__pyx_1 = 0;
  __pyx_m = Py_InitModule4("fuzzy", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_5fuzzy_Soundex) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Soundex", (PyObject *)&__pyx_type_5fuzzy_Soundex) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_ptype_5fuzzy_Soundex = &__pyx_type_5fuzzy_Soundex;
  if (PyType_Ready(&__pyx_type_5fuzzy_DMetaphone) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "DMetaphone", (PyObject *)&__pyx_type_5fuzzy_DMetaphone) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_ptype_5fuzzy_DMetaphone = &__pyx_type_5fuzzy_DMetaphone;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":59 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
  __pyx_k1 = __pyx_1;
  __pyx_1 = 0;

  /* "/home/rzoz/tmp/trunk/fuzzy/src/fuzzy.pyx":62 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("fuzzy");
}

static char *__pyx_filenames[] = {
  "fuzzy.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
